### PR TITLE
Async calls

### PR DESCRIPTION
**Pull request by putnap**
I completely removed all synchronous calls and replaced them with async variants with Async suffix as you requested.

P.S. When running acceptance tests sometimes CanCreateTcpProxyImposter fails when asserting number of requests... but only sometimes. Maybe there needs to be some delay added?

### CODE REVIEW

**Comment by mattherman** [comment]
Thanks, I will probably have time to look at this Monday morning. As for the test failure, it's a known issue (#54). I'm not sure why it happens.

**Comment by mattherman** [comment]
Sorry, it took me longer than expected to look at this. It all looks good. I'll merge this and then publish a pre-release v5 package since I still have more breaking changes I am considering before a full v5 release. I'll let you know when the package is ready.

Thanks again for taking the time to make these changes!

**Comment by putnap** [comment]
No problem, looking forward! 👍

**Comment by mattherman** [comment]
The package has been published and should be available soon.

[Package](https://www.nuget.org/packages/MbDotNet/5.0.0-rc1)
[Release Notes](https://github.com/mattherman/MbDotNet/releases/tag/v5.0.0-rc1)

Let me know if you have any issues. Unfortunately I'm probably going to be unavailable for the next week and a half.

**Pull request merged**
