### PR TITLE
Support for .NET Standard

### PR DESCRIPTION
**Pull request by mcosta91**
Hi! Sorry for the large PR and thanks for the awesome project. I need it for a .NET Core app, so I converted it to .NET Standard (test projects are targetting .NET Core).

I removed the dependency of RestSharp because RestShar.NETCore XML serialization is not working.

### CODE REVIEW

**Comment by mcosta91** [comment]
Hmm, tests are not running in appVeyor. Maybe because of this https://github.com/Microsoft/vstest/issues/596

**Comment by mattherman** [comment]
Awesome! I was hoping to do this soon anyways. I'll try to take a look over the next few days and I'll dig further into the AppVeyor issue. Thanks for the contribution.

**Comment by mattherman** [comment]
What made you choose .NET Standard 1.4 as the target? It looks like the current project is targeting .NET Framework 4.5, so going to netstandard 1.4 will be a breaking change since it is compatible with [framework 4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

I think I am fine with that since we would need to go all the way back to netstandard 1.1 in order to be compatible, but if we are going to break it anyways, is there any reason not to go to netstandard 1.6 right away (framework 4.6.2)?

EDIT: Thought about this again, I guess we would want to target the oldest netstandard version that still supports all the APIs we need in order to allow the largest number of consumers of the package.

**Comment by mattherman** [comment]
The build fails on non-Windows machines due to the assembly signing. There are multiple issues related to it, but here's [one](https://github.com/dotnet/sdk/issues/692) which links to a PR where the issue has been supposedly resolved. Just installed the latest tools, but I guess it hasn't been released yet.

Not sure what I want to do at this point. Some groups at my job require signed assemblies so I'm not interested in removing that requirement. I guess I might just need to continue building on Windows until it gets fixed.

**Comment by mattherman** [comment]
Another option would be to remove it for now and add it back in when it is supported. Those relying on the signed assemblies would simply need to remain on the current version of the library.

**Comment by mcosta91** [comment]
Hi, sorry for taking so long to respond.

About netstandard: I had some troubles trying to target older versions, but I think that was a bug with VS 2017/nuget. I also agree with you that we should target the oldest version possible in order to achieve the largest number of package consumer. Tonight (GMT-3) I'll try to target 1.3 again and see what happens.

About signed assemblies: Using signed assemblies (not building them) works today? If it works, maybe keeping it it's a good idea, since the library has more users then contributors. The only constraint will be that contributors will need to use Windows systems to build. What you think?

**Comment by mcosta91** [comment]
It does build with 1.3, against 1.2 the compiler complains about SerializableAttribute in MountebankException.

**Comment by mattherman** [comment]
Go ahead and change it to 1.3, that will get us back to .NET Framework 4.6 which should be good enough. I'll create a package to test it out and then merge it.

I'll just fix the build whenever I find time.

**Comment by mattherman** [comment]
So I generated a NuGet package with the current netstandard1.4 and attempted to install it into a project targeting .NET Framework 4.6.1. I got the following error:

```
Unable to find a version of 'Newtonsoft.Json' that is compatible with 'MbDotNet 4.0.0 constraint: Newtonsoft.Json (>= 10.0.2)'.	
```

Any idea why? The project currently references Newtonsoft.Json 8.0.1, but usually NuGet will automatically update dependent packages.

**Comment by mcosta91** [comment]
I'll try it tonight

**Comment by mcosta91** [comment]
capturar
Well, this is weird. It actually worked here. Did you try to restart VS? I had some trouble with it once.

**Comment by mattherman** [comment]
I found that I had a separate conflict in that project when trying to install Newtonsoft.Json 10.0.2 directly so I think perhaps that was causing it to be unable to install the MbDotNet package but it just didn't give a descriptive enough error. Since it worked for you, and it seems to be an issue with my specific project, I'm less worried.

Can you go ahead and push the update to have it reference netstandard1.3?

**Comment by mcosta91** [comment]
Done 👍

**Comment by mattherman** [comment]
Great. I'll merge this now and publish the package sometime this weekend.

**Comment by mattherman** [comment]
@mcosta91 I just uploaded the new 4.0.0 package. It should be available shortly. Thanks for your help with this!

**Pull request merged**
