### PR TITLE
Add specifiable content types

### PR DESCRIPTION
**Pull request by Coffee-Boyy**
Before this change I had a raw XML document I wanted to send over the wire with the XML content type but there was no way to do that easily without creating my own response object.

This fix is a proposal to allow users to specify their own content type and pass an object they want to be returned without having it be serialized.

### CODE REVIEW

**Comment by mattherman** [comment]
This functionality is already supported as you mentioned in your comment:

`var headers = new Dictionary<string, string> {{"Content-Type", "application/xml"}};`
 `imposter.AddStub().Returns(new IsResponse(HttpStatusCode.OK, myObjectAsXmlString, headers));`

The ReturnsJson and ReturnsXml methods were added as helpers since they seemed to be common use cases. Specifying specific headers would seem to be less common. 

I would support adding a helper method that took a headers dictionary, similar to the IsResponse constructor. I want to avoid creating extra types and helper methods for specific HTTP headers though.

**Comment by Coffee-Boyy** [comment]
My main point with doing it this way is less code, I don't want to have to specify a custom header dictionary header in a simple test that ONLY responds with what I specify and that content type. A specifiable content type with its own type seems pretty reasonable and does not make much clutter. It's pretty much the same as doing what you did with the custom post and get enums.

I want to be able to write a simple line of code that has everything in it, such as the predicate, and the return object/return type.

**Comment by mattherman** [comment]
I would still prefer it to take the dictionary so that the helper method can be used in a wider range of situations. The stub creation would be as follows:

`
var headers = new Dictionary<string, string> {{"Content-Type", "application/xml"}};
`
`
imposter.AddStub().Returns(HttpStatusCode.OK, myObjectAsXmlString, headers);
`

**Comment by michaelgwelch** [comment]
:+1:

**Comment by michaelgwelch** [comment]
Now this is a code review. You can even include formatted source code as part of the conversation.

**Comment by mattherman** [comment]
Tests pass, CA passes...good to go. I will merge and update the NuGet package momentarily.

**Pull request merged**
