### PR TITLE
Convert tests to xunit and update nuget packages

### PR DESCRIPTION
**Pull request by roundrobinquantum**
Converted all tests to xunit and updates test framework packages

### CODE REVIEW

**Comment by roundrobinquantum** [comment]
Hello @mattherman  could you please check my pr? Thanks

**Comment by mattherman** [comment]
My apologies. I was very busy around the end of the year so I haven't had a chance to look at this yet. I will hopefully get to it this week.

**Comment by roundrobinquantum** [comment]
Thank you Matthew


Sent from my iPhone

On 16 Jan 2024, at 02:21, Matthew Herman ***@***.***> wrote:

﻿

My apologies. I was very busy around the end of the year so I haven't had a chance to look at this yet. I will hopefully get to it this week.

**Comment by roundrobinquantum** [comment]
Hello @mattherman is there any update about this PR? Thank you

**Comment by mattherman** [comment]
I sincerely apologize for not getting around to this sooner. Thank you very much for your help.

**Pull request merged**
